image: "python:3.7.13"

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade build setuptools wheel twine
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest -v
  tags:
    - gwas
  only:
    - master
    - dev

deploy_test:
  stage: deploy
  script:
    - python -m build
    - python -m twine upload -u $PYPI_USER_TEST -p $PYPI_PWD_TEST --repository testpypi dist/*
  tags:
    - gwas
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - python -m build
    - python -m twine upload -u $PYPI_USER -p $PYPI_PWD --repository pypi dist/*
  tags:
    - gwas
  when: manual
  only:
    - tags
