image: "python:3.7"

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest -v

deploy_test:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - python -m twine upload -u $PYPI_USER_TEST -p $PYPI_PWD_TEST --repository testpypi dist/*
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - python -m twine upload -u $PYPI_USER -p $PYPI_PWD --repository pypi dist/*
  only:
    - tags