language: python
python:
  - "3.7"
branches:
  only:
  - master
  - dev
addons:
  sonarcloud:
    organization: "gwas-ebi"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - coverage run -m pytest -v
  - coverage xml
  - sonar-scanner -Dsonar.organization=gwas-ebi -Dsonar.projectKey=gwas-sumstats-validator -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=0566d66d0cfe16cd2cb8ba02db7fcd0b6d1e7ee6
